Fixing pagination for tickets which do not return a URL
DaveTCode/FreshdeskApiDotnet pull request #29
Opened 2020-11-11 10:00 UTC by keziashirazi98

2020-11-11 10:58 UTC, DaveTCode commented on FreshdeskApi.Client/FreshdeskClient.cs
> +                var contentString = response.Content.ReadAsStringAsync().Result;
There are two problems here:

1. The content is about to get turned into a stream on the line below
2. Don't call .Result in an async method, you should be using await instead.

In practice though this isn't the right way to get the information you're after. Below here you'll see on line 216-218 that I deserialize the response from Freshdesk into EITHER List<T> or PagedResult<T>. PagedResult<T> is a type which has Results and Total in it.

So you're trying to get that information again here and then further down where we already know.

The "right" fix for this bug is to have your if statement further down use the "newStylePages" boolean which tells us which type of paged data we're expecting.

I think I would reconstruct this whole section as follows:

```
if (pagingConfiguration.BeforeProcessingPageAsync != null)
                {
                    await pagingConfiguration.BeforeProcessingPageAsync(page, cancellationToken).ConfigureAwait(false);
                }

if (newStylePages) {
  var data = serializer.Deserialize<PagedResult<T>>(reader);
  var results = data?.Results;

                    if (page < 10 && url.Contains("page") && data?.Total TODO - how are you going to check that you've exhausted all pages?)
                    {
                        url = url.Replace($"page={page}", $"page={page + 1}");
                        page++;
                    }
                    else
                    {
                        morePages = false;
                    }
} else {
  var data = serializer.Deserialize<List<T>>(reader);

// Handle a link header reflecting that there's another page of data
                if (response.Headers.TryGetValues("link", out var linkHeaderValues))
                {
                    var linkHeaderValue = linkHeaderValues.FirstOrDefault();
                    if (linkHeaderValue == null || !LinkHeaderRegex.IsMatch(linkHeaderValue))
                    {
                        morePages = false;
                    }
                    else
                    {
                        var nextLinkMatch = LinkHeaderRegex.Match(linkHeaderValue);
                        url = nextLinkMatch.Groups["url"].Value;
                        page++;
                    }
                } else {
  morePages = false;
}
}
```

That's off the cuff and you shouldn't just copy paste it! It's just supposed to show the overall structure I'd expect.

2020-11-11 21:56 UTC, DaveTCode requested changes

2020-11-11 21:56 UTC, DaveTCode commented on FreshdeskApi.Client/FreshdeskClient.cs
> +                    if (newData != null && newData.Any() && page < 10 && url.Contains("page"))
What happens here if there are _fewer_ than 10 pages of data? Does the API return a 400? a 200 with no data? Either way it would be ineffecient to make requests we know we don't need to. I think you've got all the information available to you at this point to determine whether there's a page + 1.

That is, you have the total count (from the response), the page size and the current page. So current page * page size < total count => we need another page (maxing at 10 as you've done)

2020-11-12 12:45 UTC, keziashirazi98 commented on FreshdeskApi.Client/FreshdeskClient.cs
> +                    if (newData != null && newData.Any() && page < 10 && url.Contains("page"))
I can't get the 'total' because the data does not serialise into PagedResults. The following code just returns a "Newtonsoft.Json.JsonSerializationException: 'Unexpected token while deserializing object." error.
 
```
if (newStylePages)
{
      var data = serializer.Deserialize<PagedResult<T>>(reader);
}
```

2020-11-12 14:06 UTC, DaveTCode commented on FreshdeskApi.Client/FreshdeskClient.cs
> +                    if (newData != null && newData.Any() && page < 10 && url.Contains("page"))
I expect that's because you've already deserialized the results once by this point, you'll need to change it so that lines 216-218 are removed and handled somewhere else like in my original comment.

2020-11-12 15:21 UTC, merged